@section('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
@endsection

<div class="col-md-6">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <div class="col-md-5">
                Edit order
            </div>
            <div class="col-md-1 d-flex justify-content-end">
                <button class="btn-outline-primary btn" onclick="submitForm()">Save</button>
            </div>
        </div>
        <div class="card-body">
            <form id="edit-order-form" method="POST" action="{{ route('orders.update', ['id'=>$orderFormData['id']]) }}">
                @csrf
                @foreach($orderFormData['details'] as $data)
                    <div class="form-group row mb-3">
                        <label for="{{ $data['field_id'] }}" class="col-sm-3 col-form-label">{{ $data['field_name'] }}</label>
                        <div class="col-sm-9">
                            @switch($data['field_type'])
                                @case('id')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small id="{{ $data['field_id'] }}" class="form-text text-muted">This is autogenerated field and can not be edited</small>
                                    @break
                                @case('purchase sum')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small id="{{ $data['field_id'] }}" class="form-text text-muted">This field is automatically calculated and can not be edited</small>
                                    @break
                                @case('invoice')
                                    @include('main.user.order.partials._invoice_form')
                                    @break
                                @case('total purchase sum')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small id="{{ $data['field_id'] }}" class="form-text text-muted">This field is automatically calculated and can not be edited</small>
                                    @break
                                @case('total sales sum')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small id="{{ $data['field_id'] }}" class="form-text text-muted">This field is automatically calculated and can not be edited</small>
                                    @break
                                @case('profit')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small id="{{ $data['field_id'] }}" class="form-text text-muted">This field is automatically calculated and can not be edited</small>
                                    @break
                                @case('duty 7')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small id="{{ $data['field_id'] }}" class="form-text text-muted">This field is automatically calculated and can not be edited</small>
                                    @break
                                @case('duty 15')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small id="{{ $data['field_id'] }}" class="form-text text-muted">This field is automatically calculated and can not be edited</small>
                                    @break
                                @case('other costs')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small id="{{ $data['field_id'] }}" class="form-text text-muted">This field is automatically calculated and can not be edited</small>
                                    @break
                                @case('prime cost')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small id="{{ $data['field_id'] }}" class="form-text text-muted">This field is automatically calculated and can not be edited</small>
                                    @break
                                @case('sales sum')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small id="{{ $data['field_id'] }}" class="form-text text-muted">This field is automatically calculated and can not be edited</small>
                                    @break
                                @case('date')
                                    <input name="field_{{$data['field_id'] }}" type="date" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    @break
                                @case('load date')
                                    <input name="field_{{$data['field_id'] }}" type="date" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    @break
                                @case('delivery date')
                                    <input name="field_{{$data['field_id'] }}" type="date" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    @break
                                @case('file')
                                    <input disabled type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $orderFormData['uploaded_files'] }}">
                                    @break
                                @case('select status')
                                    <select class="form-control" id="{{ $data['field_id'] }}" name="field_{{$data['field_id'] }}">
                                        @foreach($data['input_select'] as $option => $color)
                                            <option value="{{ $option }}" {{ $data['value'] == $option ? ' selected' : '' }}> {{ $option }}</option>
                                        @endforeach
                                    </select>
                                    @break
                                @case('select glue')
                                    <select class="form-control" id="{{ $data['field_id'] }}" name="field_{{$data['field_id'] }}">
                                        @foreach($data['input_select'] as $option)
                                            <option value="{{ $option }}" {{ $data['value'] == $option ? ' selected' : '' }}> {{ $option }}</option>
                                        @endforeach
                                    </select>
                                    @break
                                @case('select measurement')
                                    <select class="form-control" id="{{ $data['field_id'] }}" name="field_{{$data['field_id'] }}">
                                        @foreach($data['input_select'] as $option)
                                            <option value="{{ $option }}" {{ $data['value'] == $option ? ' selected' : '' }}> {{ $option }}</option>
                                        @endforeach
                                    </select>
                                    @break
                                @case('select certification')
                                    <select class="form-control" id="{{ $data['field_id'] }}" name="field_{{$data['field_id'] }}">
                                        @foreach($data['input_select'] as $option)
                                            <option value="{{ $option }}" {{ $data['value'] == $option ? ' selected' : '' }}> {{ $option }}</option>
                                        @endforeach
                                    </select>
                                    @break
                                @case('select country')
                                    <select class="form-control" id="{{ $data['field_id'] }}" name="field_{{$data['field_id'] }}">
                                        @foreach($data['input_select'] as $option)
                                            <option value="{{ $option }}" {{ $data['value'] == $option ? ' selected' : '' }}> {{ $option }}</option>
                                        @endforeach
                                    </select>
                                    @break
                                @case('select transport')
                                    <select class="form-control" id="{{ $data['field_id'] }}" name="field_{{$data['field_id'] }}">
                                        @foreach($data['input_select'] as $option)
                                            <option value="{{ $option }}" {{ $data['value'] == $option ? ' selected' : '' }}> {{ $option }}</option>
                                        @endforeach
                                    </select>
                                    @break
                                @case('dynamic select')
                                    <select class="form-control select-with-search" id="{{ $data['field_id'] }}" name="field_{{$data['field_id'] }}">
                                        <option>-</option>
                                        @foreach($data['input_select'] as $option)
                                            <option value="{{ $option }}" {{ $data['value'] == $option ? ' selected' : '' }}> {{ $option }}</option>
                                        @endforeach
                                    </select>
                                    @break
                                @case('transport price 2')
                                    <input name="field_{{$data['field_id'] }}" type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                                    <small class="form-text text-muted">
                                        Automatic calculation based on the following invoices:
                                        <ul style="list-style-type: none;">
                                            @foreach($data['additional_data'] as $invoiceData)
                                                <li>{{$invoiceData['name']}}: <i>Nr. {{$invoiceData['number']}}</i> <b>{{$invoiceData['sum']}}€</b></li>
                                            @endforeach
                                        </ul>
                                    </small>
                                    @break
                                @default
                                    <input name="field_{{$data['field_id'] }}" type="text" class="form-control" id="{{ $data['field_id'] }}" value="{{ $data['value'] }}">
                            @endswitch
                        </div>
                    </div>
                @endforeach
            </form>
            @foreach($orderFormData['details'] as $data)
                @switch($data['field_type'])
                    @case('duty 7')
                        <div class="col-sm-9">
                            <label class="form-check-label" for="dutyToggle{{ $data['field_id'] }}">
                                Išjungti automatinius {{ $data['field_name'] }} skaičiavimus
                            </label>
                            <input {{ $data['additional_data']['settings']['disabled-auto-calculation'] ?? false ? 'checked' : '' }} class="form-check-input duty-toggle" type="checkbox" value="" id="dutyToggle{{ $data['field_id'] }}" data-field-id="{{$data['field_id']}}" data-order-id="{{$orderFormData['id']}}">
                        </div>
                    @break
                    @case('duty 15')
                        <div class="col-sm-9">
                            <label class="form-check-label" for="dutyToggle{{ $data['field_id'] }}">
                                Išjungti automatinius {{ $data['field_name'] }} skaičiavimus
                            </label>
                            <input {{ $data['additional_data']['settings']['disabled-auto-calculation'] ?? false ? 'checked' : '' }} class="form-check-input duty-toggle" type="checkbox" value="" id="dutyToggle{{ $data['field_id'] }}" data-field-id="{{$data['field_id']}}" data-order-id="{{$orderFormData['id']}}">
                        </div>
                        @break
                @endswitch
            @endforeach
        </div>
    </div>
</div>

@section('script')
    <script>
        function submitForm() {
            // Ensure the ID here matches your form's ID
            document.getElementById('edit-order-form').submit();
        }
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.select-with-search').each(function() {
                $(this).select2({
                    placeholder: "Select an option",
                    tags: true, // Allows the creation of new entries
                    createTag: function (params) {
                        var term = $.trim(params.term);
                        if (term === '') {
                            return null;
                        }
                        return {
                            id: term,
                            text: term,
                            newTag: true // Distinguishes between new and existing tags
                        };
                    }
                });
            });
        });
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Select all checkboxes with the class 'duty-toggle'
            const checkboxes = document.querySelectorAll('.duty-toggle');

            // Iterate over each checkbox to attach the change event listener
            checkboxes.forEach(function(checkbox) {
                checkbox.addEventListener('change', function() {
                    const isChecked = this.checked;
                    const fieldId = this.getAttribute('data-field-id'); // Retrieve the field ID
                    const orderId = this.getAttribute('data-order-id');
                    const form = document.querySelector('#edit-order-form'); // Select the form by ID
                    const csrfToken = form.querySelector('input[name="_token"]').value; // Get the CSRF token from the form

                    fetch('{{route("field.toggle-auto-calculations")}}', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-Requested-With': 'XMLHttpRequest',
                            'X-CSRF-TOKEN': csrfToken
                        },
                        body: JSON.stringify({
                            toggle: isChecked,
                            fieldId: fieldId,
                            orderId: orderId
                        })
                    })
                        .then(response => {
                            if (!response.ok) {
                                throw new Error('Network response was not ok');
                            }
                            return response.json();
                        })
                        .then(data => {
                            console.log('Success:', data);
                        })
                        .catch((error) => {
                            console.error('Error:', error);
                        });
                });
            });
        });
    </script>
@endsection
